version: "3"

services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: informatika # DŮLEŽITÉ: Takhle se jmenuje kontejner, který panel ovládá
    restart: unless-stopped
    ports:
      - "25565:25565" # Port pro hru
      - "8100:8100" # Port pro BlueMap (mapa)
      - "25575:25575" # DŮLEŽITÉ: Port pro RCON (ovládání panelem)
    environment:
      EULA: "TRUE"
      ONLINE_MODE: "FALSE" # Warez mode (FALSE) nebo Origo (TRUE)
      MOTD: "Skolni Server"
      ENABLE_RCON: "TRUE" # Povolit RCON
      RCON_PASSWORD: "S1N0server2021" # HESLO pro RCON - musí být stejné v panelu
      RCON_PORT: 25575
      MEMORY: "6G" # Paměť pro server
      TYPE: "PAPER" # Typ serveru (Paper je rychlejší)
    volumes:
      - ./data:/data # Ukládání dat do složky data
